### ISSUE TITLE
Paket Sorgulama İşlevi

### ISSUE THREAD

**Issue by melih** [netgsm/sms#2]
https://github.com/netgsm/sms/blob/c4dbe6effc33459159a79e839f92b63e1ba8794b/src/SmsSend.php#L627 işlevinde tek bir string ifadeden oluşan bir dizi dönüyor. Fonksiyondan dönen mevcut dizi şu şekilde,

`[ "9999 | Adet | SMS" ]`

Bunun yerine aşağıdakine benzer bir dizi dönmesi çok daha programatik olurdu,

```
[
    kalan: 9999,
    birim: "Adet",
    isim: "SMS"
]
```

**Comment by netgsm1** [comment]
Merhaba Melih Bey,

Konu değerlendirilmek üzere ilgili birime aktarılmıştır.

İyi çalışmalar dileriz.

**Comment by netgsm1** [comment]
Talebiniz üzerine gerekli iyileştirmeler yapılmıştır. paketi tekrar install ederek test edebilirsiniz.

**Comment by melih** [comment]
Teşekkürler.

```
$sms = new SmsSend;

$sms->paketsorgu()[0]['miktar']
```

ile miktara ulaşabildim. Artık `paketsorgu()` işlevinden `[ { "miktar": "7286 ", "birim": " Adet ", "paketismi": " SMS" } ]` şeklinde tek nesneden oluşan bir dizi dönüyor. Bir sonraki sürümde direkt nesneyi ya da diziyi sağlasa daha da iyi olabilir. Böylece `$sms->paketsorgu()[0]` karmaşasından kurtulabiliriz. Başarılar.

**Comment by netgsm1** [comment]
Merhaba Melih Bey, aboneliğinize bağlı birden çok paket olabilme durumundan dolayı bu şekilde dizayn edilmiştir. Örneğin 100 adet otp gibi
